package de.pixelrpg.rpg.companion;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import de.pixelrpg.rpg.config.JsonDataManager;
import org.bukkit.entity.EntityType;
import org.bukkit.plugin.Plugin;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/** Immutable runtime catalog of companion definitions. */
public final class CompanionRegistry {
    private final Map<String, CompanionDefinition> definitions;
    private final int maxLevel; private final long xpBase; private final long xpPerLevel; private final long mobKillXp; private final long questXp; private final int maxNameLength;
    private CompanionRegistry(Map<String,CompanionDefinition> definitions,int maxLevel,long xpBase,long xpPerLevel,long mobKillXp,long questXp,int maxNameLength){this.definitions=Map.copyOf(new LinkedHashMap<>(definitions));this.maxLevel=maxLevel;this.xpBase=xpBase;this.xpPerLevel=xpPerLevel;this.mobKillXp=mobKillXp;this.questXp=questXp;this.maxNameLength=maxNameLength;}
    public static CompanionRegistry load(Plugin plugin){JsonObject root=new JsonDataManager(plugin).load("companions.json"); JsonObject progression=root.getAsJsonObject("progression"); JsonObject xp=progression.getAsJsonObject("xp"); JsonObject defaults=root.getAsJsonObject("defaults"); Map<String,CompanionDefinition> result=new LinkedHashMap<>(); JsonArray definitions=root.getAsJsonArray("definitions"); if(definitions==null)throw new IllegalStateException("companions.json is missing definitions[]"); for(var e:definitions){if(!e.isJsonObject())continue; CompanionDefinition d=parse(e.getAsJsonObject()); if(result.putIfAbsent(d.id(),d)!=null)throw new IllegalStateException("Duplicate companion id: "+d.id());} if(result.isEmpty())throw new IllegalStateException("companions.json contains no definitions"); return new CompanionRegistry(result,intValue(progression,"maxLevel",99),longValue(xp,"base",100),longValue(xp,"perLevel",8),longValue(xp,"mobKill",50),longValue(xp,"questCompletion",500),intValue(defaults,"maxNameLength",24));}
    public Map<String,CompanionDefinition> definitions(){return definitions;} public Optional<CompanionDefinition> find(String id){return Optional.ofNullable(definitions.get(id));} public CompanionDefinition require(String id){return Objects.requireNonNull(definitions.get(id),"Unknown companion: "+id);} public int maxLevel(){return maxLevel;} public long xpBase(){return xpBase;} public long xpPerLevel(){return xpPerLevel;} public long mobKillXp(){return mobKillXp;} public long questXp(){return questXp;} public int maxNameLength(){return maxNameLength;}
    private static CompanionDefinition parse(JsonObject j){String id=str(j,"id","").strip();if(id.isBlank())throw new IllegalStateException("Companion id missing");String name=str(j,"name",str(j,"displayName",id)); CompanionRarity rarity=enumValue(CompanionRarity.class,str(j,"rarity","COMMON"),CompanionRarity.COMMON); EntityType type=enumValue(EntityType.class,str(j,"entityType","WOLF"),EntityType.WOLF); JsonObject visual=obj(j,"visual"); double scale=num(visual,"scale",num(j,"scale",1)); boolean renameable=bool(j,"renameable",true),adminOnly=bool(j,"adminOnly",false),passive=bool(j,"passive",true); JsonObject follow=obj(j,"follow"); CompanionDefinition.Follow f=new CompanionDefinition.Follow(bool(follow,"enabled",passive),num(follow,"startDistance",6),num(follow,"stopDistance",2.5),num(follow,"teleportDistance",48),num(follow,"movementSpeed",.34)); JsonObject combat=obj(j,"combat"); boolean unique=rarity.isUnique(); CompanionDefinition.Combat c=new CompanionDefinition.Combat(bool(combat,"enabled",bool(j,"combat",unique)),num(combat,"attackRange",3.5),num(combat,"aggroRange",unique?16:12),num(combat,"maxOwnerCombatDistance",unique?48:32),Math.max(1,(int)num(combat,"attackIntervalTicks",20)),bool(combat,"hostileTargets",true),bool(combat,"playerTargets",false),bool(combat,"friendlyTargets",false)); JsonObject mount=obj(j,"mount"); CompanionDefinition.Mount m=new CompanionDefinition.Mount(bool(mount,"enabled",false),enumValue(CompanionDefinition.Mount.Type.class,str(mount,"type","GROUND"),CompanionDefinition.Mount.Type.GROUND),Math.max(.05,num(mount,"movementSpeed",.55)),bool(mount,"requiresSaddle",true)); JsonObject p=obj(j,"progression"); CompanionDefinition.Progression pr=new CompanionDefinition.Progression(Math.clamp(intValue(p,"maxLevel",99),1,999),num(p,"healthPerLevel",.008),num(p,"damagePerLevel",.006),num(p,"speedPerLevel",.0015),num(p,"healthCap",1.8),num(p,"damageCap",1.6),num(p,"speedCap",1.15)); JsonObject eq=obj(j,"equipment"); CompanionDefinition.EquipmentDefaults ed=new CompanionDefinition.EquipmentDefaults(str(eq,"helmet",""),str(eq,"chestplate",""),str(eq,"leggings",""),str(eq,"boots",""),str(eq,"mainHand",""),str(eq,"offHand",""),eq!=null); JsonObject u=obj(j,"unlock"); CompanionDefinition.Unlock ud=new CompanionDefinition.Unlock(str(u,"type",adminOnly?"ADMIN":"DEFAULT"),str(u,"bossId","")); return new CompanionDefinition(id,name,str(j,"description",""),rarity,type,num(visual,"scale",num(j,"scale",1)),renameable,adminOnly,passive,f,c,m,pr,ed,ud,visual==null?new JsonObject():visual.deepCopy());}
    private static JsonObject obj(JsonObject p,String k){return p!=null&&p.has(k)&&p.get(k).isJsonObject()?p.getAsJsonObject(k):null;} private static String str(JsonObject p,String k,String d){return p!=null&&p.has(k)&&p.get(k).isJsonPrimitive()?p.get(k).getAsString():d;} private static boolean bool(JsonObject p,String k,boolean d){return p!=null&&p.has(k)&&p.get(k).isJsonPrimitive()?p.get(k).getAsBoolean():d;} private static double num(JsonObject p,String k,double d){return p!=null&&p.has(k)&&p.get(k).isJsonPrimitive()&&p.getAsJsonPrimitive(k).isNumber()?p.get(k).getAsDouble():d;} private static long longValue(JsonObject p,String k,long d){return p!=null&&p.has(k)&&p.get(k).isJsonPrimitive()&&p.getAsJsonPrimitive(k).isNumber()?p.get(k).getAsLong():d;} private static int intValue(JsonObject p,String k,int d){return p!=null&&p.has(k)&&p.get(k).isJsonPrimitive()&&p.getAsJsonPrimitive(k).isNumber()?p.get(k).getAsInt():d;} private static <E extends Enum<E>> E enumValue(Class<E> t,String v,E d){try{return Enum.valueOf(t,v.toUpperCase());}catch(Exception e){return d;}}
}
