package de.pixelrpg.rpg.profession;
import de.pixelrpg.rpg.dialogue.DialogueEngine;
import de.pixelrpg.rpg.npc.NpcRuntimeManager;
import de.pixelrpg.rpg.npc.RPGNpc;
import de.pixelrpg.rpg.player.PlayerProfile;
import de.pixelrpg.rpg.player.PlayerProfileManager;
import io.papermc.paper.registry.data.dialog.body.DialogBody;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import org.bukkit.entity.Player;
import java.util.*;
/** Native Paper dialog UI for profession trainers; crafting rules remain in the profession services. */
public final class ProfessionDialogService{
 private final PlayerProfileManager profiles;private final ProfessionService professions;private final CraftingService crafting;private final DialogueEngine dialogue;
 public ProfessionDialogService(PlayerProfileManager profiles,ProfessionService professions,CraftingService crafting,DialogueEngine dialogue){this.profiles=profiles;this.professions=professions;this.crafting=crafting;this.dialogue=dialogue;}
 public void openTrainer(Player player,RPGNpc npc){Profession p=npc.profession();if(p==null){dialogue.openUnavailable(player,npc.name(),"Dieser NPC hat keinen Beruf zugewiesen.");return;}PlayerProfile profile=profiles.getProfile(player.getUniqueId()).orElse(null);if(profile==null||!profile.isRegistered()){dialogue.openUnavailable(player,p.displayName(),"Du musst zuerst Rathausmitglied sein.");return;}if(!profile.hasLearnedProfession(p)){List<DialogBody> body=List.of(DialogBody.plainMessage(Component.text(p.description(),NamedTextColor.WHITE)),DialogBody.plainMessage(Component.text("Du hast diesen Beruf noch nicht erlernt.",NamedTextColor.RED)));dialogue.openMultiAction(player,p.displayComponent(),body,List.of(dialogue.actionButton(Component.text(p.displayName()+" erlernen"),NamedTextColor.GREEN,target->{if(professions.learn(target,p))openProfession(target,p);}),dialogue.actionButton(Component.text("Schließen"),NamedTextColor.GRAY,Player::closeDialog)),1);return;}openProfession(player,p);}
 public void openProfession(Player player,Profession p){PlayerProfile profile=profiles.getProfile(player.getUniqueId()).orElse(null);if(profile==null||!profile.isRegistered())return;int level=professions.getLevel(player.getUniqueId(),p);List<DialogBody> body=List.of(DialogBody.plainMessage(Component.text(p.description(),NamedTextColor.WHITE)),DialogBody.plainMessage(Component.text("Level "+level+"/"+Profession.MAX_LEVEL,NamedTextColor.AQUA)));List<io.papermc.paper.registry.data.dialog.ActionButton> actions=new ArrayList<>();List<CraftRecipe> recipes=crafting.recipes(p);actions.add(dialogue.actionButton(Component.text("Rezepte ("+recipes.size()+")"),NamedTextColor.GREEN,target->openCategories(target,p)));dialogue.openMultiAction(player,p.displayComponent(),body,actions,1);}
 private void openCategories(Player player,Profession p){List<io.papermc.paper.registry.data.dialog.ActionButton> actions=new ArrayList<>();for(CraftingCategory c:CraftingCategory.values()){long count=crafting.recipes(p).stream().filter(r->r.category()==c).count();if(count==0)continue;actions.add(dialogue.actionButton(Component.text(c.displayName()+" ("+count+")"),NamedTextColor.GREEN,target->openCategory(target,p,c)));}actions.add(dialogue.actionButton(Component.text("Zurück"),NamedTextColor.WHITE,target->openProfession(target,p)));dialogue.openMultiAction(player,Component.text(p.displayName()+" – Rezeptkategorien",NamedTextColor.GOLD),List.of(DialogBody.plainMessage(Component.text("Wähle eine Rezeptkategorie.",NamedTextColor.WHITE))),actions,2);}
 private void openCategory(Player player,Profession p,CraftingCategory c){List<CraftRecipe> recipes=crafting.recipes(p).stream().filter(r->r.category()==c).sorted(Comparator.comparingInt(CraftRecipe::requiredProfessionLevel).thenComparing(CraftRecipe::displayName)).toList();List<io.papermc.paper.registry.data.dialog.ActionButton> actions=new ArrayList<>();for(CraftRecipe r:recipes){boolean unlocked=crafting.isUnlocked(player,r);actions.add(dialogue.actionButton(Component.text(r.displayName()+(unlocked?" • freigeschaltet":" • gesperrt")),unlocked?NamedTextColor.GREEN:NamedTextColor.YELLOW,target->openRecipe(target,p,r,c)));}actions.add(dialogue.actionButton(Component.text("← Kategorien"),NamedTextColor.WHITE,target->openCategories(target,p)));dialogue.openMultiAction(player,Component.text(p.displayName()+" – "+c.displayName(),NamedTextColor.GOLD),List.of(DialogBody.plainMessage(Component.text("Berufslevel: "+professions.getLevel(player.getUniqueId(),p)+"/"+Profession.MAX_LEVEL,NamedTextColor.AQUA))),actions,2);}
 private void openRecipe(Player player,Profession p,CraftRecipe r,CraftingCategory c){boolean unlocked=crafting.isUnlocked(player,r);int level=professions.getLevel(player.getUniqueId(),p);List<DialogBody> body=new ArrayList<>();body.add(DialogBody.plainMessage(Component.text("Ergebnis: "+r.displayName(),NamedTextColor.WHITE)));body.add(DialogBody.plainMessage(Component.text("Benötigt: "+p.displayName()+" Level "+r.requiredProfessionLevel(),level>=r.requiredProfessionLevel()?NamedTextColor.AQUA:NamedTextColor.RED)));for(var e:r.costs().entrySet())body.add(DialogBody.plainMessage(Component.text("• "+e.getValue()+"x "+e.getKey().name(),NamedTextColor.WHITE)));if(!r.requiredQuestId().isBlank())body.add(DialogBody.plainMessage(Component.text("Quest: "+r.requiredQuestId(),NamedTextColor.AQUA)));if(r.unlockPrice()>0&&!unlocked)body.add(DialogBody.plainMessage(Component.text("Freischalten: "+r.unlockPrice()+" Gold",NamedTextColor.GOLD)));List<io.papermc.paper.registry.data.dialog.ActionButton> actions=new ArrayList<>();if(unlocked&&level>=r.requiredProfessionLevel())actions.add(dialogue.actionButton(Component.text("Herstellen"),NamedTextColor.GREEN,target->{var result=crafting.craft(target,r.id());target.sendMessage(Component.text(result.message(),result.success()?NamedTextColor.GREEN:NamedTextColor.RED));if(result.success())openRecipe(target,p,r,c);}));else if(!unlocked)actions.add(dialogue.actionButton(Component.text("Rezept freischalten"),NamedTextColor.YELLOW,target->{var result=crafting.unlockRecipe(target,r);target.sendMessage(Component.text(result.message(),result.success()?NamedTextColor.GREEN:NamedTextColor.RED));openRecipe(target,p,r,c);}));actions.add(dialogue.actionButton(Component.text("Zurück"),NamedTextColor.WHITE,target->openCategory(target,p,c)));dialogue.openMultiAction(player,Component.text(r.displayName(),NamedTextColor.GOLD),body,actions,1);}
}
