package de.pixelrpg.rpg.item;
import de.pixelrpg.rpg.api.ItemAPI; import net.kyori.adventure.text.Component; import org.bukkit.*; import org.bukkit.inventory.*; import org.bukkit.inventory.meta.ItemMeta; import org.bukkit.persistence.PersistentDataType; import org.bukkit.plugin.Plugin; import java.util.*;
public final class ItemService implements ItemAPI {
 private final ItemDefinitionRegistry defs; private final NamespacedKey idKey,rarityKey,categoryKey,levelKey,gearKey;
 public ItemService(Plugin p){defs=new ItemDefinitionRegistry(p);idKey=new NamespacedKey(p,"item_id");rarityKey=new NamespacedKey(p,"rarity");categoryKey=new NamespacedKey(p,"category");levelKey=new NamespacedKey(p,"required_level");gearKey=new NamespacedKey(p,"gearscore");}
 public Optional<ItemStack> createItem(Material m,ItemRarity r,int l){return defs.findByMaterial(m,r,l).map(this::create);} public Optional<ItemStack> createItem(String id){return defs.find(id).map(this::create);}
 private ItemStack create(ItemDefinition d){var item=new ItemStack(d.material());ItemMeta meta=item.getItemMeta();meta.displayName(Component.text(d.name()));var pdc=meta.getPersistentDataContainer();pdc.set(idKey,PersistentDataType.STRING,d.id());pdc.set(rarityKey,PersistentDataType.STRING,d.rarity().name());pdc.set(categoryKey,PersistentDataType.STRING,d.category().name());pdc.set(levelKey,PersistentDataType.INTEGER,d.requiredLevel());pdc.set(gearKey,PersistentDataType.DOUBLE,d.gearscoreModifier());item.setItemMeta(meta);return item;}
 public boolean isRPGItem(ItemStack i){return getItemId(i).isPresent();} public boolean isGuildItem(ItemStack i){return false;} public Optional<String> getItemId(ItemStack i){return read(i,idKey,PersistentDataType.STRING);} public Optional<ItemRarity> getRarity(ItemStack i){return read(i,rarityKey,PersistentDataType.STRING).map(ItemRarity::valueOf);} public Optional<ItemCategory> getCategory(ItemStack i){return read(i,categoryKey,PersistentDataType.STRING).map(ItemCategory::valueOf);} public Optional<ItemDefinition> getDefinition(ItemStack i){return getItemId(i).flatMap(defs::find);} public Optional<Integer> getRequiredLevel(ItemStack i){return read(i,levelKey,PersistentDataType.INTEGER);} public Optional<Double> getGearscore(ItemStack i){return read(i,gearKey,PersistentDataType.DOUBLE);}
 private <T,Z> Optional<Z> read(ItemStack i,NamespacedKey k,PersistentDataType<T,Z> t){if(i==null||i.getType().isAir()||!i.hasItemMeta())return Optional.empty();return Optional.ofNullable(i.getItemMeta().getPersistentDataContainer().get(k,t));}
}
