package de.pixelrpg.rpg;

import de.pixelrpg.rpg.api.StatisticsAPI;
import de.pixelrpg.rpg.boss.BiomeBossSpawnTask;
import de.pixelrpg.rpg.boss.BossAttackPatternRegistry;
import de.pixelrpg.rpg.boss.BossCombustListener;
import de.pixelrpg.rpg.boss.BossDamageContributionListener;
import de.pixelrpg.rpg.boss.BossDeathListener;
import de.pixelrpg.rpg.boss.BossManager;
import de.pixelrpg.rpg.boss.BossRepository;
import de.pixelrpg.rpg.boss.patterns.EnrageBuffPattern;
import de.pixelrpg.rpg.boss.patterns.ProjectileVolleyPattern;
import de.pixelrpg.rpg.boss.patterns.SlamAttackPattern;
import de.pixelrpg.rpg.boss.patterns.SummonAddsPattern;
import de.pixelrpg.rpg.command.PaperBasicCommandAdapter;
import de.pixelrpg.rpg.command.RootCommand;
import de.pixelrpg.rpg.command.impl.BossSubCommand;
import de.pixelrpg.rpg.command.impl.CompanionSubCommand;
import de.pixelrpg.rpg.command.impl.EditSubCommand;
import de.pixelrpg.rpg.command.impl.NpcSubCommand;
import de.pixelrpg.rpg.command.impl.PartySubCommand;
import de.pixelrpg.rpg.command.impl.QuestAdminSubCommand;
import de.pixelrpg.rpg.command.impl.QuestLogCommand;
import de.pixelrpg.rpg.command.impl.ShopSubCommand;
import de.pixelrpg.rpg.combat.CombatDamageListener;
import de.pixelrpg.rpg.combat.MobExperienceListener;
import de.pixelrpg.rpg.combat.SoulboundDeathListener;
import de.pixelrpg.rpg.combat.loot.LootDropListener;
import de.pixelrpg.rpg.combat.scaling.MobLevelScalingListener;
import de.pixelrpg.rpg.combat.scaling.MobNameplateListener;
import de.pixelrpg.rpg.combat.scaling.MobNameplateService;
import de.pixelrpg.rpg.combat.scaling.MobScalingConfig;
import de.pixelrpg.rpg.combat.skill.SkillInputListener;
import de.pixelrpg.rpg.combat.skill.WeaponAbilityEngine;
import de.pixelrpg.rpg.companion.CompanionExperienceListener;
import de.pixelrpg.rpg.companion.CompanionService;
import de.pixelrpg.rpg.core.LifecycleCoordinator;
import de.pixelrpg.rpg.core.RPGKeys;
import de.pixelrpg.rpg.dialogue.DialogueCommand;
import de.pixelrpg.rpg.dialogue.DialogueEngine;
import de.pixelrpg.rpg.dialogue.QuickActionsDialogListener;
import de.pixelrpg.rpg.dialogue.QuickActionsDialogService;
import de.pixelrpg.rpg.dialogue.StoryNpcDialogue;
import de.pixelrpg.rpg.economy.GuildCurrencyItemFactory;
import de.pixelrpg.rpg.economy.GuildCurrencyPickupListener;
import de.pixelrpg.rpg.equipment.EquipmentService;
import de.pixelrpg.rpg.gui.CraftingGUI;
import de.pixelrpg.rpg.gui.GUIListener;
import de.pixelrpg.rpg.gui.ShopEditorGUI;
import de.pixelrpg.rpg.item.ItemDefinitionRegistry;
import de.pixelrpg.rpg.item.ItemDisplayNameResolver;
import de.pixelrpg.rpg.item.ItemEconomyConfig;
import de.pixelrpg.rpg.item.ItemService;
import de.pixelrpg.rpg.item.RPGItemBuilder;
import de.pixelrpg.rpg.npc.NpcBehaviorRegistry;
import de.pixelrpg.rpg.npc.NpcChunkListener;
import de.pixelrpg.rpg.npc.NpcInteractListener;
import de.pixelrpg.rpg.npc.NpcLookTask;
import de.pixelrpg.rpg.npc.NpcManager;
import de.pixelrpg.rpg.npc.NpcType;
import de.pixelrpg.rpg.npc.behavior.BankerBehavior;
import de.pixelrpg.rpg.npc.behavior.FillerBehavior;
import de.pixelrpg.rpg.npc.behavior.ProfessionTrainerBehavior;
import de.pixelrpg.rpg.npc.behavior.QuestBehavior;
import de.pixelrpg.rpg.npc.behavior.ReceptionBehavior;
import de.pixelrpg.rpg.npc.behavior.ShopBehavior;
import de.pixelrpg.rpg.npc.behavior.StoryBehavior;
import de.pixelrpg.rpg.npc.behavior.TravelBehavior;
import de.pixelrpg.rpg.party.PartyDisconnectListener;
import de.pixelrpg.rpg.party.PartyManager;
import de.pixelrpg.rpg.player.PlayerProfileLifecycleListener;
import de.pixelrpg.rpg.player.PlayerProfileManager;
import de.pixelrpg.rpg.profession.Profession;
import de.pixelrpg.rpg.profession.ProfessionSystem;
import de.pixelrpg.rpg.quest.GlobalEventState;
import de.pixelrpg.rpg.quest.QuestManager;
import de.pixelrpg.rpg.quest.QuestMobKillListener;
import de.pixelrpg.rpg.quest.QuestPassiveCheckTask;
import de.pixelrpg.rpg.quest.QuestRepository;
import de.pixelrpg.rpg.scoreboard.PlaytimeTracker;
import de.pixelrpg.rpg.scoreboard.ScoreboardService;
import de.pixelrpg.rpg.shop.ShopManager;
import de.pixelrpg.rpg.stats.MobKillStatisticListener;
import de.pixelrpg.rpg.stats.PlayerDeathStatisticListener;
import de.pixelrpg.rpg.stats.QuestBossStatisticListener;
import de.pixelrpg.rpg.stats.RPGStatsListener;
import de.pixelrpg.rpg.stats.StatEngine;
import de.pixelrpg.rpg.stats.StatisticsService;
import de.pixelrpg.rpg.story.StoryBookFactory;
import de.pixelrpg.rpg.story.StoryManager;
import de.pixelrpg.rpg.travel.GuildCompassListener;
import de.pixelrpg.rpg.guild.GuildManager;
import de.pixelrpg.rpg.region.RegionEditor;
import de.pixelrpg.rpg.region.RegionListener;
import de.pixelrpg.rpg.region.RegionManager;
import de.pixelrpg.rpg.region.RegionRepository;
import de.pixelrpg.rpg.region.RegionSpawnService;
import io.papermc.paper.plugin.lifecycle.event.types.LifecycleEvents;
import org.bukkit.Bukkit;
import org.bukkit.plugin.ServicePriority;
import org.bukkit.plugin.java.JavaPlugin;

public final class PixelRPGPlugin extends JavaPlugin {
    private static PixelRPGPlugin instance;
    private final LifecycleCoordinator lifecycle = new LifecycleCoordinator();
    private PlayerProfileManager playerProfileManager;
    private StatEngine statEngine;
    private ProfessionSystem professionSystem;
    private ItemDisplayNameResolver itemDisplayNameResolver;
    private ItemEconomyConfig itemEconomyConfig;
    private ItemService itemService;
    private EquipmentService equipmentService;
    private CraftingGUI craftingGUI;
    private MobScalingConfig mobScalingConfig;
    private MobNameplateService mobNameplateService;
    private MobLevelScalingListener mobLevelScalingListener;
    private NpcManager npcManager;
    private NpcBehaviorRegistry npcBehaviorRegistry;
    private NpcLookTask npcLookTask;
    private BankerBehavior bankerBehavior;
    private ShopManager shopManager;
    private ShopEditorGUI shopEditorGUI;
    private StoryManager storyManager;
    private PartyManager partyManager;
    private QuestRepository questRepository;
    private QuestManager questManager;
    private QuestPassiveCheckTask questPassiveCheckTask;
    private GlobalEventState globalEventState;
    private BossRepository bossRepository;
    private BossManager bossManager;
    private BiomeBossSpawnTask biomeBossSpawnTask;
    private StatisticsService statisticsService;
    private ScoreboardService scoreboardService;
    private PlaytimeTracker playtimeTracker;
    private CompanionService companionService;
    private CombatDamageListener combatDamageListener;
    private RegionManager regionManager;
    private RegionEditor regionEditor;
    private RegionSpawnService regionSpawnService;
    private GuildManager guildManager;

    @Override
    public void onEnable() {
        instance = this;
        saveDefaultConfig();
        RPGKeys.init(this);
        StoryBookFactory.load(getConfig());
        GuildCurrencyItemFactory.configureMaxStackSize(getConfig().getInt("economy.currency.max-stack-size", 64));
        playerProfileManager = new PlayerProfileManager(this);
        playerProfileManager.initialize(getConfig());
        getServer().getPluginManager().registerEvents(new PlayerProfileLifecycleListener(playerProfileManager), this);
        statEngine = new StatEngine(playerProfileManager);
        professionSystem = new ProfessionSystem(this, playerProfileManager);
        professionSystem.register();
        itemDisplayNameResolver = new ItemDisplayNameResolver(new ItemDefinitionRegistry(this), professionSystem.craftingRecipeRegistry());
        WeaponAbilityEngine weaponAbilityEngine = new WeaponAbilityEngine(playerProfileManager, statEngine);
        itemEconomyConfig = new ItemEconomyConfig();
        itemEconomyConfig.load(getConfig());
        RPGItemBuilder.configureScaling(this);
        itemService = new ItemService(this);
        equipmentService = new EquipmentService(playerProfileManager, statEngine, itemService);
        Bukkit.getServicesManager().register(de.pixelrpg.rpg.api.ItemAPI.class, itemService, this, ServicePriority.Normal);
        craftingGUI = new CraftingGUI(professionSystem.craftingService(), playerProfileManager);
        mobScalingConfig = new MobScalingConfig();
        mobScalingConfig.load(getConfig());
        mobNameplateService = new MobNameplateService(this, mobScalingConfig);
        shopManager = new ShopManager(this);
        shopManager.load();
        shopEditorGUI = new ShopEditorGUI(shopManager);
        storyManager = new StoryManager(this, playerProfileManager);
        storyManager.load();
        partyManager = new PartyManager(this);
        Bukkit.getServicesManager().register(de.pixelrpg.rpg.api.PartyAPI.class, partyManager, this, ServicePriority.Normal);
        questRepository = new QuestRepository(this);
        questRepository.load();
        globalEventState = new GlobalEventState(this);
        globalEventState.load();
        questManager = new QuestManager(this, questRepository, playerProfileManager, playerProfileManager, globalEventState, partyManager.getShareRange());
        guildManager = GuildManager.getInstance(this, playerProfileManager);
        RegionRepository regionRepository = new RegionRepository(getDataFolder(), getLogger());
        regionManager = new RegionManager(regionRepository);
        regionManager.load();
        regionEditor = new RegionEditor(this, regionManager);
        regionEditor.start();
        regionSpawnService = new RegionSpawnService(this, regionManager);
        regionSpawnService.start();
        getServer().getPluginManager().registerEvents(new RegionListener(regionManager, regionEditor, regionSpawnService), this);
        BossAttackPatternRegistry patternRegistry = new BossAttackPatternRegistry();
        patternRegistry.register(new SlamAttackPattern());
        patternRegistry.register(new SummonAddsPattern());
        patternRegistry.register(new ProjectileVolleyPattern());
        patternRegistry.register(new EnrageBuffPattern());
        bossRepository = new BossRepository(this);
        bossRepository.load();
        bossManager = new BossManager(this, patternRegistry, playerProfileManager, partyManager, playerProfileManager, itemService, mobScalingConfig,
                getConfig().getDouble("bosses.bar-radius", 60.0D), getConfig().getInt("bosses.bar-update-interval-ticks", 20), getConfig().getInt("bosses.phase-check-interval-ticks", 10));
        biomeBossSpawnTask = new BiomeBossSpawnTask(this, bossRepository, bossManager, getConfig().getDouble("bosses.biome-spawn.spawn-radius", 80.0D),
                getConfig().getInt("bosses.biome-spawn.check-interval-seconds", 60), getConfig().getInt("bosses.biome-spawn.max-concurrent", 4));
        biomeBossSpawnTask.start();
        statisticsService = new StatisticsService(playerProfileManager);
        Bukkit.getServicesManager().register(StatisticsAPI.class, statisticsService, this, ServicePriority.Normal);
        scoreboardService = new ScoreboardService(this, playerProfileManager, getConfig().getInt("scoreboard.update-interval-ticks", 20));
        scoreboardService.startTask();
        playtimeTracker = new PlaytimeTracker(this, playerProfileManager);
        playtimeTracker.startAutosaveTask(getConfig().getInt("statistics.autosave-interval-ticks", 6000));
        npcManager = new NpcManager(this);
        npcManager.loadAll();
        getServer().getPluginManager().registerEvents(new NpcChunkListener(npcManager), this);
        npcLookTask = new NpcLookTask(this, npcManager, getConfig().getDouble("npc.look-radius", 3.0),
                getConfig().getDouble("npc.nameplate-radius", 5.0), getConfig().getInt("npc.look-interval-ticks", 5));
        npcLookTask.start();
        DialogueEngine dialogueEngine = new DialogueEngine();
        StoryNpcDialogue storyNpcDialogue = new StoryNpcDialogue(playerProfileManager, dialogueEngine);
        QuickActionsDialogService quickActions = new QuickActionsDialogService(playerProfileManager, statEngine, questManager, itemService);
        companionService = new CompanionService(this);
        npcBehaviorRegistry = new NpcBehaviorRegistry();
        npcBehaviorRegistry.register(new ReceptionBehavior(playerProfileManager, dialogueEngine, partyManager));
        npcBehaviorRegistry.register(new QuestBehavior(questManager, playerProfileManager, dialogueEngine));
        npcBehaviorRegistry.register(new ShopBehavior(shopManager, playerProfileManager, dialogueEngine));
        npcBehaviorRegistry.register(new TravelBehavior(npcManager, playerProfileManager, dialogueEngine));
        npcBehaviorRegistry.register(new StoryBehavior(storyManager, storyNpcDialogue, dialogueEngine, playerProfileManager));
        bankerBehavior = new BankerBehavior(playerProfileManager, dialogueEngine);
        npcBehaviorRegistry.register(bankerBehavior);
        npcBehaviorRegistry.register(new FillerBehavior(questManager, playerProfileManager, dialogueEngine));
        npcBehaviorRegistry.register(new ProfessionTrainerBehavior(NpcType.PROFESSION_BLACKSMITH, Profession.BLACKSMITH, playerProfileManager, professionSystem.professionService(), dialogueEngine, quickActions));
        npcBehaviorRegistry.register(new ProfessionTrainerBehavior(NpcType.PROFESSION_SCHOLAR, Profession.SCHOLAR, playerProfileManager, professionSystem.professionService(), dialogueEngine, quickActions));
        getServer().getPluginManager().registerEvents(new NpcInteractListener(npcManager, npcBehaviorRegistry, companionService), this);
        getServer().getPluginManager().registerEvents(new MobLevelScalingListener(this, mobScalingConfig, playerProfileManager, statEngine), this);
        getServer().getPluginManager().registerEvents(new MobNameplateListener(mobNameplateService), this);
        getServer().getPluginManager().registerEvents(new CombatDamageListener(playerProfileManager, statEngine, partyManager), this);
        getServer().getPluginManager().registerEvents(new MobExperienceListener(playerProfileManager, statEngine), this);
        getServer().getPluginManager().registerEvents(new LootDropListener(this, playerProfileManager, itemService), this);
        getServer().getPluginManager().registerEvents(new SoulboundDeathListener(playerProfileManager, itemService), this);
        getServer().getPluginManager().registerEvents(new CompanionExperienceListener(companionService), this);
        getServer().getPluginManager().registerEvents(new CompanionService.Listener(companionService), this);
        getServer().getPluginManager().registerEvents(new PartyDisconnectListener(partyManager), this);
        getServer().getPluginManager().registerEvents(new GuildCurrencyPickupListener(this, playerProfileManager), this);
        getServer().getPluginManager().registerEvents(new PlayerDeathStatisticListener(statisticsService, playerProfileManager), this);
        getServer().getPluginManager().registerEvents(new MobKillStatisticListener(statisticsService), this);
        getServer().getPluginManager().registerEvents(new QuestBossStatisticListener(statisticsService), this);
        getServer().getPluginManager().registerEvents(new RPGStatsListener(statisticsService), this);
        getServer().getPluginManager().registerEvents(new QuestMobKillListener(questManager), this);
        questPassiveCheckTask = new QuestPassiveCheckTask(this, questManager);
        questPassiveCheckTask.start();
        getServer().getPluginManager().registerEvents(new QuickActionsDialogListener(quickActions), this);
        registerCommands();
    }

    private void registerCommands() {
        RootCommand rootCommand = new RootCommand();
        rootCommand.register(new BossSubCommand(bossManager));
        rootCommand.register(new CompanionSubCommand(companionService));
        rootCommand.register(new EditSubCommand(npcManager));
        rootCommand.register(new NpcSubCommand(npcManager));
        rootCommand.register(new PartySubCommand(partyManager));
        rootCommand.register(new QuestAdminSubCommand(questManager));
        rootCommand.register(new QuestLogCommand(questManager));
        rootCommand.register(new ShopSubCommand(shopManager));
        Bukkit.getCommandMap().register("pixelrpg", new PaperBasicCommandAdapter(rootCommand));
    }

    @Override
    public void onDisable() {
        lifecycle.shutdown();
        if (questPassiveCheckTask != null) questPassiveCheckTask.stop();
        if (npcLookTask != null) npcLookTask.stop();
        if (npcManager != null) npcManager.shutdown();
        if (regionSpawnService != null) regionSpawnService.stop();
        if (regionEditor != null) regionEditor.stop();
        if (bossManager != null) bossManager.shutdown();
        if (biomeBossSpawnTask != null) biomeBossSpawnTask.stop();
        if (scoreboardService != null) scoreboardService.stopTask();
        if (playtimeTracker != null) playtimeTracker.stop();
        if (professionSystem != null) professionSystem.shutdown();
        if (playerProfileManager != null) playerProfileManager.shutdown();
        instance = null;
    }

    public static PixelRPGPlugin getInstance() {
        return instance;
    }
}
