        getServer().getPluginManager().registerEvents(craftingGUI, this);
        getServer().getPluginManager().registerEvents(new RPGStatsListener(statEngine, playerProfileManager), this);
        getServer().getPluginManager().registerEvents(new SkillInputListener(weaponAbilityEngine), this);
        getServer().getPluginManager().registerEvents(blacksmithGUI, this);
        getServer().getPluginManager().registerEvents(shopEditorGUI, this);
        getServer().getPluginManager().registerEvents(new LootDropListener(playerProfileManager, itemEconomyConfig), this);
        MobLevelScalingListener mobLevelScalingListener = new MobLevelScalingListener(this, playerProfileManager, mobScalingConfig);
        getServer().getPluginManager().registerEvents(mobLevelScalingListener, this);
        mobLevelScalingListener.start();
        getServer().getPluginManager().registerEvents(new MobNameplateListener(mobNameplateService, playerProfileManager), this);
        getServer().getPluginManager().registerEvents(new CombatDamageListener(playerProfileManager, playerProfileManager, statEngine, mobScalingConfig), this);
        getServer().getPluginManager().registerEvents(new BossDamageContributionListener(bossManager, playerProfileManager), this);
        getServer().getPluginManager().registerEvents(new MobExperienceListener(playerProfileManager, mobScalingConfig), this);
        getServer().getPluginManager().registerEvents(new NpcInteractListener(npcManager, npcBehaviorRegistry, questManager), this);
        getServer().getPluginManager().registerEvents(new QuestMobKillListener(questManager), this);
        getServer().getPluginManager().registerEvents(new QuestExperienceScalingListener(), this);
        getServer().getPluginManager().registerEvents(new PartyDisconnectListener(partyManager), this);
        getServer().getPluginManager().registerEvents(new BossDeathListener(bossManager), this);
        getServer().getPluginManager().registerEvents(new MobKillStatisticListener(playerProfileManager, statisticsService), this);
        getServer().getPluginManager().registerEvents(new PlayerDeathStatisticListener(playerProfileManager, statisticsService), this);
        getServer().getPluginManager().registerEvents(new QuestBossStatisticListener(statisticsService), this);
        getServer().getPluginManager().registerEvents(new GuildCurrencyPickupListener(playerProfileManager, playerProfileManager), this);
        getServer().getPluginManager().registerEvents(new GuildCompassListener(npcManager, playerProfileManager), this);
        getServer().getPluginManager().registerEvents(new SoulboundDeathListener(playerProfileManager), this);
        getServer().getPluginManager().registerEvents(scoreboardService, this);
        getServer().getPluginManager().registerEvents(playtimeTracker, this);